<?php

namespace SmallOverload;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use SmallOverload\Event\NotCalledEvent;
use SmallOverload\Event\SmallOverloadEvent;
use SmallOverload\Listener;

class EventServiceProvider extends ServiceProvider
{
    /** @var array */
    protected $listen = [
        SmallOverloadEvent::class => [
            Listener\SmallOverload1Listener::class,
            Listener\SmallOverload2Listener::class,
            Listener\SmallOverload3Listener::class,
            Listener\SmallOverload4Listener::class,
            Listener\SmallOverload5Listener::class,
            Listener\SmallOverload6Listener::class,
            Listener\SmallOverload7Listener::class,
            Listener\SmallOverload8Listener::class,
            Listener\SmallOverload9Listener::class,
            Listener\SmallOverload10Listener::class,
            Listener\SmallOverload11Listener::class,
            Listener\SmallOverload12Listener::class,
            Listener\SmallOverload13Listener::class,
            Listener\SmallOverload14Listener::class,
            Listener\SmallOverload15Listener::class,
            Listener\SmallOverload16Listener::class,
            Listener\SmallOverload17Listener::class,
            Listener\SmallOverload18Listener::class,
            Listener\SmallOverload19Listener::class,
            Listener\SmallOverload20Listener::class,
            Listener\SmallOverload21Listener::class,
            Listener\SmallOverload22Listener::class,
            Listener\SmallOverload23Listener::class,
            Listener\SmallOverload24Listener::class,
            Listener\SmallOverload25Listener::class
        ],
        NotCalledEvent::class => [
            Listener\NotCalled1Listener::class,
            Listener\NotCalled2Listener::class,
            Listener\NotCalled3Listener::class,
            Listener\NotCalled4Listener::class,
            Listener\NotCalled5Listener::class,
            Listener\NotCalled6Listener::class,
            Listener\NotCalled7Listener::class,
            Listener\NotCalled8Listener::class,
            Listener\NotCalled9Listener::class,
            Listener\NotCalled10Listener::class,
            Listener\NotCalled11Listener::class,
            Listener\NotCalled12Listener::class,
            Listener\NotCalled13Listener::class,
            Listener\NotCalled14Listener::class,
            Listener\NotCalled15Listener::class,
            Listener\NotCalled16Listener::class,
            Listener\NotCalled17Listener::class,
            Listener\NotCalled18Listener::class,
            Listener\NotCalled19Listener::class,
            Listener\NotCalled20Listener::class,
            Listener\NotCalled21Listener::class,
            Listener\NotCalled22Listener::class,
            Listener\NotCalled23Listener::class,
            Listener\NotCalled24Listener::class,
            Listener\NotCalled25Listener::class,
            Listener\NotCalled26Listener::class,
            Listener\NotCalled27Listener::class,
            Listener\NotCalled28Listener::class,
            Listener\NotCalled29Listener::class,
            Listener\NotCalled30Listener::class,
            Listener\NotCalled31Listener::class,
            Listener\NotCalled32Listener::class,
            Listener\NotCalled33Listener::class,
            Listener\NotCalled34Listener::class,
            Listener\NotCalled35Listener::class,
            Listener\NotCalled36Listener::class,
            Listener\NotCalled37Listener::class,
            Listener\NotCalled38Listener::class,
            Listener\NotCalled39Listener::class,
            Listener\NotCalled40Listener::class,
            Listener\NotCalled41Listener::class,
            Listener\NotCalled42Listener::class,
            Listener\NotCalled43Listener::class,
            Listener\NotCalled44Listener::class,
            Listener\NotCalled45Listener::class,
            Listener\NotCalled46Listener::class,
            Listener\NotCalled47Listener::class,
            Listener\NotCalled48Listener::class,
            Listener\NotCalled49Listener::class,
            Listener\NotCalled50Listener::class,
            Listener\NotCalled51Listener::class,
            Listener\NotCalled52Listener::class,
            Listener\NotCalled53Listener::class,
            Listener\NotCalled54Listener::class,
            Listener\NotCalled55Listener::class,
            Listener\NotCalled56Listener::class,
            Listener\NotCalled57Listener::class,
            Listener\NotCalled58Listener::class,
            Listener\NotCalled59Listener::class,
            Listener\NotCalled60Listener::class,
            Listener\NotCalled61Listener::class,
            Listener\NotCalled62Listener::class,
            Listener\NotCalled63Listener::class,
            Listener\NotCalled64Listener::class,
            Listener\NotCalled65Listener::class,
            Listener\NotCalled66Listener::class,
            Listener\NotCalled67Listener::class,
            Listener\NotCalled68Listener::class,
            Listener\NotCalled69Listener::class,
            Listener\NotCalled70Listener::class,
            Listener\NotCalled71Listener::class,
            Listener\NotCalled72Listener::class,
            Listener\NotCalled73Listener::class,
            Listener\NotCalled74Listener::class,
            Listener\NotCalled75Listener::class
        ],
    ];
}
