component:
    slug: laravel
benchmark:
    type: hello-world
    relativeUrl: /benchmark/helloworld
sourceCode:
    entryPoint: public/index.php
coreDependency:
    name: laravel/framework
    version: 7.7.1
